import { createContext, useContext, useEffect, useMemo, useState } from 'react';

type Theme = 'dark' | 'light';
export type Language = 'pt' | 'en' | 'es' | 'ca';
export type AccessibilityFontScale = 'normal' | 'large' | 'x-large';
export type AccessibilityReadingProfile = 'default' | 'mild' | 'moderate' | 'strong';

type AccessibilitySettings = {
  highContrast: boolean;
  reducedMotion: boolean;
  readingProfile: AccessibilityReadingProfile;
  fontScale: AccessibilityFontScale;
};

type Dict = Record<string, string>;

const dictionaries: Record<Language, Dict> = {
  pt: {
    nav_medhub: 'Centro Medico',
    nav_dashboard: 'Dashboard',
    nav_planner: 'Planner',
    nav_flashcards: 'Flashcards',
    nav_schedule: 'Cronograma',
      nav_question_bank: 'Banco de Questões',
    nav_analytics: 'Analises',
    nav_tigas: 'Tigas Voice',
    nav_reminders: 'Lembretes',
    nav_pomodoro: 'Relógio Inteligente',
    nav_mindmap: 'Mapa Mental',
    nav_settings: 'Configuracoes',
    nav_how_to_study: 'Como Estudar',
    nav_summaries: 'Resumos',
    nav_courses: 'Cursos',
    nav_manuals: 'Manuais',
    nav_notes: 'Anotações',
    nav_lessons: 'Estratégia de Estudos',
    nav_stories: 'Histórias',
    nav_community: 'Comunidade',
    plan_free: 'Plano Gratuito',
    plan_premium: 'PREMIUM',
    theme_toggle: 'Trocar tema',
    language_label: 'Idioma',
    logout: 'Sair',
    reminders: 'Lembretes',
    map: 'Mapa',
    conversation_mode: 'Modo conversa',
    ai_model: 'Modelo de IA',
    tigas_listening: 'Ouvindo...',
    tigas_speaking: 'Falando...',
    tigas_idle: 'Assistente de Estudos por Voz',
    tigas_placeholder: 'Digite ou clique no microfone para falar...',
    app_close_menu: 'Fechar menu',
    app_open_sidebar: 'Abrir menu lateral',
    app_close_sidebar: 'Fechar menu lateral',
    app_requires_certification_access: 'Requer certificacao de CNPJ/CRM para acesso',
    app_requires_certification_badge: 'Requer certificacao',
    app_subscribe_premium: 'Assinar Premium',
    app_from_price: 'R$19,90/mes',
    settings_title: 'Configuracoes',
    settings_subtitle: 'Gerencie suas informacoes e preferencias',
    settings_profile_info: 'Informacoes do Perfil',
    settings_profile_name: 'Nome completo',
    settings_profile_email_ro: 'E-mail (nao editavel)',
    settings_profile_area: 'Area de estudo',
    settings_profile_goal: 'Objetivo principal',
    settings_profile_goal_ph: 'Ex: Passar na residencia medica USP 2025',
    settings_profile_whatsapp: 'WhatsApp para alertas importantes',
    settings_profile_whatsapp_ph: '(31) 99999-9999',
    settings_profile_whatsapp_help: 'Enviamos lembretes de provas e trabalhos nesse numero.',
    settings_profile_weekly_goal: 'Meta semanal de estudos',
    settings_save_changes: 'Salvar alteracoes',
    settings_saving: 'Salvando...',
    settings_password_change: 'Alterar Senha',
    settings_password_current: 'Senha atual',
    settings_password_new: 'Nova senha',
    settings_password_new_ph: 'Minimo 6 caracteres',
    settings_password_confirm: 'Confirmar nova senha',
    settings_password_confirm_ph: 'Repita a nova senha',
    settings_change_password: 'Alterar senha',
    settings_changing: 'Alterando...',
    settings_account_info: 'Informacoes da Conta',
    settings_plan_current: 'Plano atual',
    settings_member_since: 'Membro desde',
    settings_area: 'Area',
    settings_not_defined: 'Nao definida',
    settings_app_prefs: 'Preferencias do App',
    settings_accessibility: 'Acessibilidade',
    settings_accessibility_desc: 'Ajuste contraste, movimento e tamanho do texto em toda a plataforma.',
    settings_high_contrast: 'Alto contraste',
    settings_high_contrast_desc: 'Aumenta o contraste de textos, bordas e superficies.',
    settings_reduce_motion: 'Reduzir animacoes',
    settings_reduce_motion_desc: 'Diminui transicoes, efeitos e movimentos automáticos.',
    settings_dyslexia_friendly: 'Leitura facilitada',
    settings_dyslexia_friendly_desc: 'Ajusta fonte, espacamento e hierarquia visual para leitura mais confortavel.',
    settings_reading_profile: 'Perfil de leitura',
    settings_reading_profile_desc: 'Escolha a intensidade para facilitar leitura e foco.',
    settings_reading_default: 'Padrao',
    settings_reading_mild: 'Leve',
    settings_reading_moderate: 'Moderada',
    settings_reading_strong: 'Alta',
    accessibility_onboarding_title: 'Personalize sua leitura',
    accessibility_onboarding_desc: 'Ative um perfil de leitura para reduzir cansaco visual desde o primeiro acesso.',
    accessibility_onboarding_apply: 'Aplicar perfil',
    accessibility_onboarding_keep_default: 'Manter padrao',
    accessibility_onboarding_later: 'Agora nao',
    settings_font_size: 'Tamanho do texto',
    settings_font_normal: 'Padrao',
    settings_font_large: 'Grande',
    settings_font_xlarge: 'Extra grande',
    settings_theme: 'Tema',
    settings_theme_dark: 'Dark',
    settings_theme_light: 'Light',
    settings_language: 'Idioma',
    settings_auto_voice_login: 'Voz automatica no login',
    settings_auto_voice_desc: 'Saudacao por horario + leitura dos lembretes importantes do dia.',
    settings_enabled: 'Ativado',
    settings_disabled: 'Desativado',
    settings_voice_profile: 'Perfil de Voz Adaptativo',
    settings_voice_profile_desc: 'A IA ajusta ritmo e timbre com base nos seus sinais implicitos de uso.',
    settings_loading_voice_profile: 'Carregando perfil de voz...',
    settings_manual_layer: 'Camada manual de voz',
    settings_saving_preset: 'Salvando...',
    settings_signal_interruptions: 'Interrupcoes',
    settings_signal_repeats: 'Comandos repetidos',
    settings_signal_toggles: 'Voz desligada',
    settings_voice_trend_week: 'Tendencia da ultima semana',
    settings_days_with_history: 'dia(s) com historico',
    settings_current_rate_adjust: 'Ajuste atual de ritmo',
    settings_current_pitch_adjust: 'Ajuste atual de timbre',
    settings_last_signal: 'Ultimo sinal recebido em',
    settings_no_signals: 'Ainda nao ha sinais suficientes para adaptacao automatica.',
    settings_profile_reading: 'Leitura automatica do perfil',
    settings_reset_adaptation: 'Resetar adaptacao',
    settings_reset_adaptation_desc: 'Apaga o aprendizado acumulado e volta a voz ao perfil base do modelo da IA.',
    settings_reset: 'Resetar',
    settings_resetting: 'Resetando...',
    settings_trend_stable: 'Estavel',
    settings_trend_light: 'Ajuste leve',
    settings_trend_moderate: 'Ajuste moderado',
    settings_trend_intense: 'Ajuste intenso',
    settings_recommend_auto: 'Modo automatico ativo: a IA combina seu historico recente com o modelo atual de voz.',
    settings_recommend_calm: 'Preset manual prioriza uma fala mais lenta e suave, acima dos ajustes automaticos.',
    settings_recommend_objective: 'Preset manual prioriza respostas mais diretas e com menos cadencia emocional.',
    settings_recommend_energetic: 'Preset manual prioriza uma fala mais animada e com maior presenca.',
    settings_recommend_interruptions: 'Ha varias interrupcoes recentes; a voz esta sendo desacelerada para ficar menos invasiva.',
    settings_recommend_repeats: 'Comandos repetidos sugerem baixa clareza; o sistema reduz timbre e aceleracao para ganhar compreensao.',
    settings_recommend_toggles: 'Voce desligou a voz algumas vezes; o sistema tende a manter uma presenca vocal menos insistente.',
    settings_recommend_stable: 'Ainda nao ha sinais negativos relevantes nesta semana; o perfil esta estavel.',
    settings_preset_auto: 'Automatico',
    settings_preset_auto_desc: 'Deixa a IA ajustar a voz sozinha com base no seu uso.',
    settings_preset_calm: 'Mais calma',
    settings_preset_calm_desc: 'Fala mais suave, lenta e menos incisiva.',
    settings_preset_objective: 'Mais objetiva',
    settings_preset_objective_desc: 'Mais direta, compacta e levemente mais rapida.',
    settings_preset_energetic: 'Mais energetica',
    settings_preset_energetic_desc: 'Mais vibrante, animada e com presenca maior.',
    settings_profile_updated: 'Perfil atualizado com sucesso!',
    settings_password_updated: 'Senha alterada com sucesso!',
    settings_voice_reset_ok: 'Perfil de voz resetado com sucesso.',
    settings_voice_load_error: 'Nao foi possivel carregar o perfil de voz adaptativo.',
    settings_voice_reset_error: 'Nao foi possivel resetar a adaptacao de voz.',
    settings_voice_preset_error: 'Nao foi possivel salvar o modo manual de voz.',
    dash_greeting_morning: 'Bom dia',
    dash_greeting_afternoon: 'Boa tarde',
    dash_greeting_evening: 'Boa noite',
    dash_summary_subtitle: 'Aqui esta o resumo dos seus estudos.',
    dash_unlock_features: 'Desbloqueie todos os recursos',
    dash_unlock_desc: 'Planner, Flashcards, Cronograma e Analises disponiveis a partir de',
    dash_subscribe: 'Assinar',
    dash_streak_days: 'dias seguidos',
    dash_week: 'Semana',
    dash_tasks_completed: 'tarefas concluidas',
    dash_created: 'criados',
    dash_weekly_goal: 'Meta Semanal',
    dash_hours_studied_of: 'estudadas de',
    dash_last7days: 'Ultimos 7 dias',
    dash_quick_access: 'Acesso Rapido',
    dash_in_progress: 'em andamento',
    dash_cards: 'cards',
    dash_schedule_view_week: 'Ver semana',
    dash_analytics_view_progress: 'Ver progresso',
    dash_pomodoro_quick: 'Pomodoro Rapido',
    dash_pomodoro_desc: 'Inicie agora um ciclo de foco de 25 minutos com 1 clique.',
    dash_open_timer: 'Abrir Timer',
    dash_start_now: 'Iniciar Agora',
    dash_my_goal: 'Meu objetivo',
    dash_area_label: 'Area:',
    dash_goal_label: 'Meta:',
    dash_weekly_goal_label: 'Meta semanal:',
  },
  en: {
    nav_medhub: 'Medical Hub',
    nav_dashboard: 'Dashboard',
    nav_planner: 'Planner',
    nav_flashcards: 'Flashcards',
    nav_schedule: 'Schedule',
      nav_question_bank: 'Question Bank',
    nav_analytics: 'Analytics',
    nav_tigas: 'Tigas Voice',
    nav_reminders: 'Reminders',
    nav_pomodoro: 'Pomodoro',
    nav_mindmap: 'Mind Map',
    nav_settings: 'Settings',
    nav_how_to_study: 'How to Study',
    nav_summaries: 'Summaries',
    nav_courses: 'Courses',
    nav_manuals: 'Manuals',
    nav_notes: 'Notes',
    nav_lessons: 'Lessons',
    nav_stories: 'Stories',
    nav_community: 'Community',
    plan_free: 'Free Plan',
    plan_premium: 'PREMIUM',
    theme_toggle: 'Switch theme',
    language_label: 'Language',
    logout: 'Sign out',
    reminders: 'Reminders',
    map: 'Map',
    conversation_mode: 'Conversation mode',
    ai_model: 'AI model',
    tigas_listening: 'Listening...',
    tigas_speaking: 'Speaking...',
    tigas_idle: 'Voice Study Assistant',
    tigas_placeholder: 'Type or click the microphone to speak...',
    app_close_menu: 'Close menu',
    app_open_sidebar: 'Open sidebar',
    app_close_sidebar: 'Close sidebar',
    app_requires_certification_access: 'CNPJ/CRM certification required to access',
    app_requires_certification_badge: 'Requires certification',
    app_subscribe_premium: 'Go Premium',
    app_from_price: 'R$19.90/month',
    settings_title: 'Settings',
    settings_subtitle: 'Manage your profile and preferences',
    settings_profile_info: 'Profile Information',
    settings_profile_name: 'Full name',
    settings_profile_email_ro: 'Email (read-only)',
    settings_profile_area: 'Study area',
    settings_profile_goal: 'Main goal',
    settings_profile_goal_ph: 'Ex: Pass medical residency USP 2025',
    settings_profile_whatsapp: 'WhatsApp for important alerts',
    settings_profile_whatsapp_ph: '(31) 99999-9999',
    settings_profile_whatsapp_help: 'We send exam and assignment reminders to this number.',
    settings_profile_weekly_goal: 'Weekly study goal',
    settings_save_changes: 'Save changes',
    settings_saving: 'Saving...',
    settings_password_change: 'Change Password',
    settings_password_current: 'Current password',
    settings_password_new: 'New password',
    settings_password_new_ph: 'Minimum 6 characters',
    settings_password_confirm: 'Confirm new password',
    settings_password_confirm_ph: 'Repeat new password',
    settings_change_password: 'Change password',
    settings_changing: 'Changing...',
    settings_account_info: 'Account Information',
    settings_plan_current: 'Current plan',
    settings_member_since: 'Member since',
    settings_area: 'Area',
    settings_not_defined: 'Not set',
    settings_app_prefs: 'App Preferences',
    settings_accessibility: 'Accessibility',
    settings_accessibility_desc: 'Adjust contrast, motion and text size across the entire platform.',
    settings_high_contrast: 'High contrast',
    settings_high_contrast_desc: 'Increases the contrast of text, borders and surfaces.',
    settings_reduce_motion: 'Reduce motion',
    settings_reduce_motion_desc: 'Reduces transitions, effects and automatic movements.',
    settings_dyslexia_friendly: 'Reading friendly mode',
    settings_dyslexia_friendly_desc: 'Adjusts font, spacing and visual hierarchy for easier reading.',
    settings_reading_profile: 'Reading profile',
    settings_reading_profile_desc: 'Choose the intensity to improve readability and focus.',
    settings_reading_default: 'Default',
    settings_reading_mild: 'Mild',
    settings_reading_moderate: 'Moderate',
    settings_reading_strong: 'High',
    accessibility_onboarding_title: 'Personalize your reading',
    accessibility_onboarding_desc: 'Enable a reading profile to reduce visual fatigue from your first visit.',
    accessibility_onboarding_apply: 'Apply profile',
    accessibility_onboarding_keep_default: 'Keep default',
    accessibility_onboarding_later: 'Not now',
    settings_font_size: 'Text size',
    settings_font_normal: 'Default',
    settings_font_large: 'Large',
    settings_font_xlarge: 'Extra large',
    settings_theme: 'Theme',
    settings_theme_dark: 'Dark',
    settings_theme_light: 'Light',
    settings_language: 'Language',
    settings_auto_voice_login: 'Auto voice on login',
    settings_auto_voice_desc: 'Time-based greeting + important reminders readout.',
    settings_enabled: 'Enabled',
    settings_disabled: 'Disabled',
    settings_voice_profile: 'Adaptive Voice Profile',
    settings_voice_profile_desc: 'AI adjusts rhythm and tone from your implicit usage signals.',
    settings_loading_voice_profile: 'Loading voice profile...',
    settings_manual_layer: 'Manual voice layer',
    settings_saving_preset: 'Saving...',
    settings_signal_interruptions: 'Interruptions',
    settings_signal_repeats: 'Repeated commands',
    settings_signal_toggles: 'Voice turned off',
    settings_voice_trend_week: 'Last week trend',
    settings_days_with_history: 'day(s) with history',
    settings_current_rate_adjust: 'Current rate adjustment',
    settings_current_pitch_adjust: 'Current pitch adjustment',
    settings_last_signal: 'Last signal received at',
    settings_no_signals: 'No enough signals for automatic adaptation yet.',
    settings_profile_reading: 'Automatic profile reading',
    settings_reset_adaptation: 'Reset adaptation',
    settings_reset_adaptation_desc: 'Clears learned behavior and returns to base model profile.',
    settings_reset: 'Reset',
    settings_resetting: 'Resetting...',
    settings_trend_stable: 'Stable',
    settings_trend_light: 'Light adjustment',
    settings_trend_moderate: 'Moderate adjustment',
    settings_trend_intense: 'Intense adjustment',
    settings_recommend_auto: 'Automatic mode is active: AI combines recent history with the current voice model.',
    settings_recommend_calm: 'Manual preset prioritizes a slower and softer delivery over automatic adjustments.',
    settings_recommend_objective: 'Manual preset prioritizes direct answers with less emotional cadence.',
    settings_recommend_energetic: 'Manual preset prioritizes a more energetic and vivid voice.',
    settings_recommend_interruptions: 'Several recent interruptions detected; voice is being slowed down to feel less intrusive.',
    settings_recommend_repeats: 'Repeated commands suggest low clarity; system reduces timbre and acceleration for comprehension.',
    settings_recommend_toggles: 'Voice was turned off multiple times; system keeps vocal presence less insistent.',
    settings_recommend_stable: 'No relevant negative signals this week; profile is stable.',
    settings_preset_auto: 'Automatic',
    settings_preset_auto_desc: 'Lets AI tune your voice based on usage.',
    settings_preset_calm: 'Calmer',
    settings_preset_calm_desc: 'Softer, slower and less incisive voice.',
    settings_preset_objective: 'More objective',
    settings_preset_objective_desc: 'More direct and slightly faster delivery.',
    settings_preset_energetic: 'More energetic',
    settings_preset_energetic_desc: 'More vibrant and expressive voice.',
    settings_profile_updated: 'Profile updated successfully!',
    settings_password_updated: 'Password changed successfully!',
    settings_voice_reset_ok: 'Voice profile reset successfully.',
    settings_voice_load_error: 'Could not load adaptive voice profile.',
    settings_voice_reset_error: 'Could not reset voice adaptation.',
    settings_voice_preset_error: 'Could not save manual voice mode.',
    dash_greeting_morning: 'Good morning',
    dash_greeting_afternoon: 'Good afternoon',
    dash_greeting_evening: 'Good evening',
    dash_summary_subtitle: 'Here is your study summary.',
    dash_unlock_features: 'Unlock all features',
    dash_unlock_desc: 'Planner, Flashcards, Schedule and Analytics available from',
    dash_subscribe: 'Subscribe',
    dash_streak_days: 'days in a row',
    dash_week: 'Week',
    dash_tasks_completed: 'tasks completed',
    dash_created: 'created',
    dash_weekly_goal: 'Weekly Goal',
    dash_hours_studied_of: 'studied of',
    dash_last7days: 'Last 7 days',
    dash_quick_access: 'Quick Access',
    dash_in_progress: 'in progress',
    dash_cards: 'cards',
    dash_schedule_view_week: 'View week',
    dash_analytics_view_progress: 'View progress',
    dash_pomodoro_quick: 'Quick Pomodoro',
    dash_pomodoro_desc: 'Start a 25-minute focus cycle now with one click.',
    dash_open_timer: 'Open Timer',
    dash_start_now: 'Start Now',
    dash_my_goal: 'My goal',
    dash_area_label: 'Area:',
    dash_goal_label: 'Goal:',
    dash_weekly_goal_label: 'Weekly goal:',
  },
  es: {
    nav_medhub: 'Centro Medico',
    nav_dashboard: 'Panel',
    nav_planner: 'Planificador',
    nav_flashcards: 'Tarjetas',
      nav_question_bank: 'Banco de Preguntas',
    nav_schedule: 'Cronograma',
    nav_analytics: 'Analiticas',
    nav_tigas: 'Tigas Voz',
    nav_reminders: 'Recordatorios',
    nav_pomodoro: 'Pomodoro',
    nav_mindmap: 'Mapa Mental',
    nav_settings: 'Configuracion',
    nav_how_to_study: 'Cómo Estudiar',
    nav_summaries: 'Resúmenes',
    nav_courses: 'Cursos',
    nav_manuals: 'Manuales',
    nav_notes: 'Notas',
    nav_lessons: 'Clases',
    nav_stories: 'Historias',
    nav_community: 'Comunidad',
    plan_free: 'Plan Gratis',
    plan_premium: 'PREMIUM',
    theme_toggle: 'Cambiar tema',
    language_label: 'Idioma',
    logout: 'Salir',
    reminders: 'Recordatorios',
    map: 'Mapa',
    conversation_mode: 'Modo conversacion',
    ai_model: 'Modelo de IA',
    tigas_listening: 'Escuchando...',
    tigas_speaking: 'Hablando...',
    tigas_idle: 'Asistente de Estudio por Voz',
    tigas_placeholder: 'Escribe o usa el microfono para hablar...',
    app_close_menu: 'Cerrar menu',
    app_open_sidebar: 'Abrir menu lateral',
    app_close_sidebar: 'Cerrar menu lateral',
    app_requires_certification_access: 'Se requiere certificacion CNPJ/CRM para acceder',
    app_requires_certification_badge: 'Requiere certificacion',
    app_subscribe_premium: 'Suscribirse Premium',
    app_from_price: 'R$19,90/mes',
    settings_title: 'Configuracion',
    settings_subtitle: 'Administra tu perfil y preferencias',
    settings_profile_info: 'Informacion del Perfil',
    settings_profile_name: 'Nombre completo',
    settings_profile_email_ro: 'Correo (no editable)',
    settings_profile_area: 'Area de estudio',
    settings_profile_goal: 'Objetivo principal',
    settings_profile_goal_ph: 'Ej: Aprobar residencia medica USP 2025',
    settings_profile_whatsapp: 'WhatsApp para alertas importantes',
    settings_profile_whatsapp_ph: '(31) 99999-9999',
    settings_profile_whatsapp_help: 'Enviamos recordatorios de examenes y trabajos a este numero.',
    settings_profile_weekly_goal: 'Meta semanal de estudio',
    settings_save_changes: 'Guardar cambios',
    settings_saving: 'Guardando...',
    settings_password_change: 'Cambiar Contrasena',
    settings_password_current: 'Contrasena actual',
    settings_password_new: 'Nueva contrasena',
    settings_password_new_ph: 'Minimo 6 caracteres',
    settings_password_confirm: 'Confirmar nueva contrasena',
    settings_password_confirm_ph: 'Repite la nueva contrasena',
    settings_change_password: 'Cambiar contrasena',
    settings_changing: 'Cambiando...',
    settings_account_info: 'Informacion de la Cuenta',
    settings_plan_current: 'Plan actual',
    settings_member_since: 'Miembro desde',
    settings_area: 'Area',
    settings_not_defined: 'No definida',
    settings_app_prefs: 'Preferencias de la App',
    settings_accessibility: 'Accesibilidad',
    settings_accessibility_desc: 'Ajusta contraste, movimiento y tamano de texto en toda la plataforma.',
    settings_high_contrast: 'Alto contraste',
    settings_high_contrast_desc: 'Aumenta el contraste de textos, bordes y superficies.',
    settings_reduce_motion: 'Reducir animaciones',
    settings_reduce_motion_desc: 'Disminuye transiciones, efectos y movimientos automaticos.',
    settings_dyslexia_friendly: 'Lectura facilitada',
    settings_dyslexia_friendly_desc: 'Ajusta fuente, espaciado y jerarquia visual para una lectura mas comoda.',
    settings_reading_profile: 'Perfil de lectura',
    settings_reading_profile_desc: 'Elige la intensidad para facilitar lectura y enfoque.',
    settings_reading_default: 'Predeterminado',
    settings_reading_mild: 'Leve',
    settings_reading_moderate: 'Moderada',
    settings_reading_strong: 'Alta',
    accessibility_onboarding_title: 'Personaliza tu lectura',
    accessibility_onboarding_desc: 'Activa un perfil de lectura para reducir fatiga visual desde el primer acceso.',
    accessibility_onboarding_apply: 'Aplicar perfil',
    accessibility_onboarding_keep_default: 'Mantener predeterminado',
    accessibility_onboarding_later: 'Ahora no',
    settings_font_size: 'Tamano del texto',
    settings_font_normal: 'Predeterminado',
    settings_font_large: 'Grande',
    settings_font_xlarge: 'Extra grande',
    settings_theme: 'Tema',
    settings_theme_dark: 'Dark',
    settings_theme_light: 'Light',
    settings_language: 'Idioma',
    settings_auto_voice_login: 'Voz automatica al iniciar sesion',
    settings_auto_voice_desc: 'Saludo por horario + lectura de recordatorios importantes del dia.',
    settings_enabled: 'Activado',
    settings_disabled: 'Desactivado',
    settings_voice_profile: 'Perfil de Voz Adaptativo',
    settings_voice_profile_desc: 'La IA ajusta ritmo y timbre segun tus senales implicitas de uso.',
    settings_loading_voice_profile: 'Cargando perfil de voz...',
    settings_manual_layer: 'Capa manual de voz',
    settings_saving_preset: 'Guardando...',
    settings_signal_interruptions: 'Interrupciones',
    settings_signal_repeats: 'Comandos repetidos',
    settings_signal_toggles: 'Voz desactivada',
    settings_voice_trend_week: 'Tendencia de la ultima semana',
    settings_days_with_history: 'dia(s) con historial',
    settings_current_rate_adjust: 'Ajuste actual de ritmo',
    settings_current_pitch_adjust: 'Ajuste actual de timbre',
    settings_last_signal: 'Ultima senal recibida en',
    settings_no_signals: 'Aun no hay senales suficientes para adaptacion automatica.',
    settings_profile_reading: 'Lectura automatica del perfil',
    settings_reset_adaptation: 'Reiniciar adaptacion',
    settings_reset_adaptation_desc: 'Borra el aprendizaje acumulado y vuelve al perfil base del modelo.',
    settings_reset: 'Reiniciar',
    settings_resetting: 'Reiniciando...',
    settings_trend_stable: 'Estable',
    settings_trend_light: 'Ajuste leve',
    settings_trend_moderate: 'Ajuste moderado',
    settings_trend_intense: 'Ajuste intenso',
    settings_recommend_auto: 'Modo automatico activo: la IA combina historial reciente con el modelo actual de voz.',
    settings_recommend_calm: 'El preset manual prioriza una voz mas suave y lenta por encima del ajuste automatico.',
    settings_recommend_objective: 'El preset manual prioriza respuestas directas con menos cadencia emocional.',
    settings_recommend_energetic: 'El preset manual prioriza una voz mas animada y expresiva.',
    settings_recommend_interruptions: 'Hay varias interrupciones recientes; la voz se esta desacelerando para ser menos invasiva.',
    settings_recommend_repeats: 'Los comandos repetidos sugieren baja claridad; el sistema reduce timbre y aceleracion.',
    settings_recommend_toggles: 'Desactivaste la voz varias veces; el sistema mantiene una presencia vocal menos insistente.',
    settings_recommend_stable: 'No hay senales negativas relevantes esta semana; el perfil esta estable.',
    settings_preset_auto: 'Automatico',
    settings_preset_auto_desc: 'Deja que la IA ajuste la voz segun tu uso.',
    settings_preset_calm: 'Mas calma',
    settings_preset_calm_desc: 'Voz mas suave, lenta y menos incisiva.',
    settings_preset_objective: 'Mas objetiva',
    settings_preset_objective_desc: 'Voz mas directa y levemente mas rapida.',
    settings_preset_energetic: 'Mas energetica',
    settings_preset_energetic_desc: 'Voz mas vibrante y expresiva.',
    settings_profile_updated: 'Perfil actualizado con exito!',
    settings_password_updated: 'Contrasena cambiada con exito!',
    settings_voice_reset_ok: 'Perfil de voz reiniciado con exito.',
    settings_voice_load_error: 'No se pudo cargar el perfil de voz adaptativo.',
    settings_voice_reset_error: 'No se pudo reiniciar la adaptacion de voz.',
    settings_voice_preset_error: 'No se pudo guardar el modo manual de voz.',
    dash_greeting_morning: 'Buenos dias',
    dash_greeting_afternoon: 'Buenas tardes',
    dash_greeting_evening: 'Buenas noches',
    dash_summary_subtitle: 'Aqui esta el resumen de tus estudios.',
    dash_unlock_features: 'Desbloquea todos los recursos',
    dash_unlock_desc: 'Planner, Flashcards, Cronograma y Analiticas disponibles desde',
    dash_subscribe: 'Suscribirse',
    dash_streak_days: 'dias seguidos',
    dash_week: 'Semana',
    dash_tasks_completed: 'tareas completadas',
    dash_created: 'creados',
    dash_weekly_goal: 'Meta Semanal',
    dash_hours_studied_of: 'estudiadas de',
    dash_last7days: 'Ultimos 7 dias',
    dash_quick_access: 'Acceso rapido',
    dash_in_progress: 'en progreso',
    dash_cards: 'tarjetas',
    dash_schedule_view_week: 'Ver semana',
    dash_analytics_view_progress: 'Ver progreso',
    dash_pomodoro_quick: 'Pomodoro rapido',
    dash_pomodoro_desc: 'Inicia ahora un ciclo de enfoque de 25 minutos con 1 clic.',
    dash_open_timer: 'Abrir Timer',
    dash_start_now: 'Iniciar ahora',
    dash_my_goal: 'Mi objetivo',
    dash_area_label: 'Area:',
    dash_goal_label: 'Meta:',
    dash_weekly_goal_label: 'Meta semanal:',
  },
  ca: {
    nav_medhub: 'Centre Medic',
    nav_dashboard: 'Tauler',
    nav_planner: 'Planificador',
    nav_flashcards: 'Fitxes',
      nav_question_bank: 'Banc de Preguntes',
    nav_schedule: 'Calendari',
    nav_analytics: 'Analitiques',
    nav_tigas: 'Tigas Veu',
    nav_reminders: 'Recordatoris',
    nav_pomodoro: 'Pomodoro',
    nav_mindmap: 'Mapa Mental',
    nav_settings: 'Configuracio',
    nav_how_to_study: 'Com Estudiar',
    nav_summaries: 'Resums',
    nav_courses: 'Cursos',
    nav_manuals: 'Manuals',
    nav_notes: 'Notes',
    nav_lessons: 'Classes',
    nav_stories: 'Històries',
    nav_community: 'Comunitat',
    plan_free: 'Pla Gratuit',
    plan_premium: 'PREMIUM',
    theme_toggle: 'Canviar tema',
    language_label: 'Idioma',
    logout: 'Sortir',
    reminders: 'Recordatoris',
    map: 'Mapa',
    conversation_mode: 'Mode conversa',
    ai_model: "Model d'IA",
    tigas_listening: 'Escoltant...',
    tigas_speaking: 'Parlant...',
    tigas_idle: "Assistent d'Estudi per Veu",
    tigas_placeholder: 'Escriu o prem el microfon per parlar...',
    app_close_menu: 'Tancar menu',
    app_open_sidebar: 'Obrir menu lateral',
    app_close_sidebar: 'Tancar menu lateral',
    app_requires_certification_access: "Cal certificacio CNPJ/CRM per accedir",
    app_requires_certification_badge: 'Cal certificacio',
    app_subscribe_premium: 'Subscriu Premium',
    app_from_price: 'R$19,90/mes',
    settings_title: 'Configuracio',
    settings_subtitle: 'Gestiona el teu perfil i preferencies',
    settings_profile_info: 'Informacio del Perfil',
    settings_profile_name: 'Nom complet',
    settings_profile_email_ro: 'Correu (no editable)',
    settings_profile_area: "Area d'estudi",
    settings_profile_goal: 'Objectiu principal',
    settings_profile_goal_ph: 'Ex: Aprovar residencia medica USP 2025',
    settings_profile_whatsapp: 'WhatsApp per avisos importants',
    settings_profile_whatsapp_ph: '(31) 99999-9999',
    settings_profile_whatsapp_help: "Enviem recordatoris d'examens i treballs a aquest numero.",
    settings_profile_weekly_goal: "Objectiu setmanal d'estudi",
    settings_save_changes: 'Desar canvis',
    settings_saving: 'Desant...',
    settings_password_change: 'Canviar contrasenya',
    settings_password_current: 'Contrasenya actual',
    settings_password_new: 'Nova contrasenya',
    settings_password_new_ph: 'Minim 6 caracters',
    settings_password_confirm: 'Confirmar nova contrasenya',
    settings_password_confirm_ph: 'Repeteix la nova contrasenya',
    settings_change_password: 'Canviar contrasenya',
    settings_changing: 'Canviant...',
    settings_account_info: 'Informacio del Compte',
    settings_plan_current: 'Pla actual',
    settings_member_since: 'Membre des de',
    settings_area: 'Area',
    settings_not_defined: 'No definida',
    settings_app_prefs: "Preferencies de l'App",
    settings_accessibility: 'Accessibilitat',
    settings_accessibility_desc: 'Ajusta contrast, moviment i mida del text a tota la plataforma.',
    settings_high_contrast: 'Alt contrast',
    settings_high_contrast_desc: 'Augmenta el contrast de textos, vores i superficies.',
    settings_reduce_motion: 'Reduir animacions',
    settings_reduce_motion_desc: 'Redueix transicions, efectes i moviments automatics.',
    settings_dyslexia_friendly: 'Lectura facilitada',
    settings_dyslexia_friendly_desc: 'Ajusta font, espaiat i jerarquia visual per a una lectura mes comoda.',
    settings_reading_profile: 'Perfil de lectura',
    settings_reading_profile_desc: 'Tria la intensitat per facilitar lectura i concentracio.',
    settings_reading_default: 'Predeterminat',
    settings_reading_mild: 'Lleu',
    settings_reading_moderate: 'Moderada',
    settings_reading_strong: 'Alta',
    accessibility_onboarding_title: 'Personalitza la teva lectura',
    accessibility_onboarding_desc: 'Activa un perfil de lectura per reduir la fatiga visual des del primer accés.',
    accessibility_onboarding_apply: 'Aplicar perfil',
    accessibility_onboarding_keep_default: 'Mantenir predeterminat',
    accessibility_onboarding_later: 'Ara no',
    settings_font_size: 'Mida del text',
    settings_font_normal: 'Predeterminat',
    settings_font_large: 'Gran',
    settings_font_xlarge: 'Extra gran',
    settings_theme: 'Tema',
    settings_theme_dark: 'Dark',
    settings_theme_light: 'Light',
    settings_language: 'Idioma',
    settings_auto_voice_login: "Veu automatica en iniciar sessio",
    settings_auto_voice_desc: 'Salutacio per horari + lectura de recordatoris importants del dia.',
    settings_enabled: 'Activat',
    settings_disabled: 'Desactivat',
    settings_voice_profile: 'Perfil de Veu Adaptatiu',
    settings_voice_profile_desc: "La IA ajusta ritme i timbre segons els teus senyals implicits d'us.",
    settings_loading_voice_profile: 'Carregant perfil de veu...',
    settings_manual_layer: 'Capa manual de veu',
    settings_saving_preset: 'Desant...',
    settings_signal_interruptions: 'Interrupcions',
    settings_signal_repeats: 'Comandes repetides',
    settings_signal_toggles: 'Veu desactivada',
    settings_voice_trend_week: "Tendencia de l'ultima setmana",
    settings_days_with_history: 'dia(es) amb historial',
    settings_current_rate_adjust: 'Ajust actual de ritme',
    settings_current_pitch_adjust: 'Ajust actual de timbre',
    settings_last_signal: 'Ultim senyal rebut a',
    settings_no_signals: "Encara no hi ha senyals suficients per a l'adaptacio automatica.",
    settings_profile_reading: 'Lectura automatica del perfil',
    settings_reset_adaptation: 'Reiniciar adaptacio',
    settings_reset_adaptation_desc: "Esborra l'aprenentatge acumulat i torna al perfil base.",
    settings_reset: 'Reiniciar',
    settings_resetting: 'Reiniciant...',
    settings_trend_stable: 'Estable',
    settings_trend_light: 'Ajust lleu',
    settings_trend_moderate: 'Ajust moderat',
    settings_trend_intense: 'Ajust intens',
    settings_recommend_auto: 'Mode automatic actiu: la IA combina historial recent amb el model de veu actual.',
    settings_recommend_calm: 'El preset manual prioritza una veu mes suau i lenta.',
    settings_recommend_objective: 'El preset manual prioritza respostes mes directes.',
    settings_recommend_energetic: 'El preset manual prioritza una veu mes energetica.',
    settings_recommend_interruptions: "Hi ha diverses interrupcions recents; la veu s'alenteix per ser menys invasiva.",
    settings_recommend_repeats: 'Comandes repetides suggereixen baixa claredat; el sistema ajusta timbre i ritme.',
    settings_recommend_toggles: "Has desactivat la veu diverses vegades; el sistema redueix la presencia vocal.",
    settings_recommend_stable: 'No hi ha senyals negatives rellevants aquesta setmana; el perfil es estable.',
    settings_preset_auto: 'Automatic',
    settings_preset_auto_desc: "Deixa que la IA ajusti la veu segons l'us.",
    settings_preset_calm: 'Mes calma',
    settings_preset_calm_desc: 'Veu mes suau, lenta i menys incisiva.',
    settings_preset_objective: 'Mes objectiva',
    settings_preset_objective_desc: 'Veu mes directa i una mica mes rapida.',
    settings_preset_energetic: 'Mes energetica',
    settings_preset_energetic_desc: 'Veu mes vibrant i expressiva.',
    settings_profile_updated: 'Perfil actualitzat correctament!',
    settings_password_updated: 'Contrasenya canviada correctament!',
    settings_voice_reset_ok: 'Perfil de veu reiniciat correctament.',
    settings_voice_load_error: 'No s\'ha pogut carregar el perfil de veu adaptatiu.',
    settings_voice_reset_error: 'No s\'ha pogut reiniciar l\'adaptacio de veu.',
    settings_voice_preset_error: 'No s\'ha pogut desar el mode manual de veu.',
    dash_greeting_morning: 'Bon dia',
    dash_greeting_afternoon: 'Bona tarda',
    dash_greeting_evening: 'Bona nit',
    dash_summary_subtitle: 'Aqui tens el resum dels teus estudis.',
    dash_unlock_features: 'Desbloqueja tots els recursos',
    dash_unlock_desc: 'Planner, Flashcards, Calendari i Analitiques disponibles des de',
    dash_subscribe: 'Subscriure',
    dash_streak_days: 'dies seguits',
    dash_week: 'Setmana',
    dash_tasks_completed: 'tasques completades',
    dash_created: 'creats',
    dash_weekly_goal: 'Objectiu Setmanal',
    dash_hours_studied_of: 'estudiades de',
    dash_last7days: 'Ultims 7 dies',
    dash_quick_access: 'Acces rapid',
    dash_in_progress: 'en curs',
    dash_cards: 'fitxes',
    dash_schedule_view_week: 'Veure setmana',
    dash_analytics_view_progress: 'Veure progres',
    dash_pomodoro_quick: 'Pomodoro rapid',
    dash_pomodoro_desc: 'Inicia ara un cicle de focus de 25 minuts amb 1 clic.',
    dash_open_timer: 'Obrir Timer',
    dash_start_now: 'Iniciar ara',
    dash_my_goal: 'El meu objectiu',
    dash_area_label: 'Area:',
    dash_goal_label: 'Meta:',
    dash_weekly_goal_label: 'Meta setmanal:',
  },
};

type PreferencesContextValue = {
  theme: Theme;
  language: Language;
  accessibility: AccessibilitySettings;
  isAccessibilityOnboardingOpen: boolean;
  setTheme: (theme: Theme) => void;
  toggleTheme: () => void;
  setLanguage: (language: Language) => void;
  setHighContrast: (enabled: boolean) => void;
  setReducedMotion: (enabled: boolean) => void;
  setReadingProfile: (profile: AccessibilityReadingProfile) => void;
  closeAccessibilityOnboarding: () => void;
  setFontScale: (scale: AccessibilityFontScale) => void;
  t: (key: string) => string;
};

const PreferencesContext = createContext<PreferencesContextValue | undefined>(undefined);

export function PreferencesProvider({ children }: { children: React.ReactNode }) {
  const readingProfileOptions = ['default', 'mild', 'moderate', 'strong'] as const;
  const [theme, setThemeState] = useState<Theme>(() => {
    const saved = localStorage.getItem('app.theme');
    return saved === 'light' ? 'light' : 'dark';
  });
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app.language');
    if (saved === 'en' || saved === 'es' || saved === 'ca' || saved === 'pt') return saved;
    return 'pt';
  });
  const [highContrast, setHighContrastState] = useState<boolean>(() => localStorage.getItem('app.accessibility.highContrast') === 'true');
  const [reducedMotion, setReducedMotionState] = useState<boolean>(() => {
    const saved = localStorage.getItem('app.accessibility.reducedMotion');
    if (saved === 'true') return true;
    if (saved === 'false') return false;
    return typeof window !== 'undefined' && window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  });
  const [readingProfile, setReadingProfileState] = useState<AccessibilityReadingProfile>(() => {
    const savedProfile = localStorage.getItem('app.accessibility.readingProfile');
    if (savedProfile && (readingProfileOptions as readonly string[]).includes(savedProfile)) {
      return savedProfile as AccessibilityReadingProfile;
    }
    const legacy = localStorage.getItem('app.accessibility.dyslexiaFriendly') === 'true';
    return legacy ? 'moderate' : 'default';
  });
  const [isAccessibilityOnboardingOpen, setIsAccessibilityOnboardingOpen] = useState<boolean>(() => {
    return localStorage.getItem('app.accessibility.onboardingSeen') !== 'true';
  });
  const [fontScale, setFontScaleState] = useState<AccessibilityFontScale>(() => {
    const saved = localStorage.getItem('app.accessibility.fontScale');
    if (saved === 'large' || saved === 'x-large' || saved === 'normal') return saved;
    return 'normal';
  });

  useEffect(() => {
    localStorage.setItem('app.theme', theme);
    const body = document.body;
    body.classList.remove('theme-dark', 'theme-light');
    body.classList.add(theme === 'light' ? 'theme-light' : 'theme-dark');
  }, [theme]);

  useEffect(() => {
    localStorage.setItem('app.language', language);
  }, [language]);

  useEffect(() => {
    localStorage.setItem('app.accessibility.highContrast', String(highContrast));
    document.body.classList.toggle('accessibility-high-contrast', highContrast);
  }, [highContrast]);

  useEffect(() => {
    localStorage.setItem('app.accessibility.reducedMotion', String(reducedMotion));
    document.body.classList.toggle('accessibility-reduced-motion', reducedMotion);
  }, [reducedMotion]);

  useEffect(() => {
    localStorage.setItem('app.accessibility.readingProfile', readingProfile);
    const body = document.body;
    body.classList.remove('accessibility-reading-mild', 'accessibility-reading-moderate', 'accessibility-reading-strong');
    if (readingProfile !== 'default') {
      body.classList.add(`accessibility-reading-${readingProfile}`);
    }
    localStorage.setItem('app.accessibility.dyslexiaFriendly', String(readingProfile !== 'default'));
  }, [readingProfile]);

  useEffect(() => {
    localStorage.setItem('app.accessibility.fontScale', fontScale);
    const root = document.documentElement;
    root.classList.remove('font-scale-normal', 'font-scale-large', 'font-scale-x-large');
    root.classList.add(`font-scale-${fontScale}`);
  }, [fontScale]);

  const value = useMemo<PreferencesContextValue>(() => ({
    theme,
    language,
    accessibility: {
      highContrast,
      reducedMotion,
      readingProfile,
      fontScale,
    },
    isAccessibilityOnboardingOpen,
    setTheme: (next) => setThemeState(next),
    toggleTheme: () => setThemeState((prev) => (prev === 'dark' ? 'light' : 'dark')),
    setLanguage: (next) => setLanguageState(next),
    setHighContrast: (enabled) => setHighContrastState(enabled),
    setReducedMotion: (enabled) => setReducedMotionState(enabled),
    setReadingProfile: (profile) => setReadingProfileState(profile),
    closeAccessibilityOnboarding: () => {
      localStorage.setItem('app.accessibility.onboardingSeen', 'true');
      setIsAccessibilityOnboardingOpen(false);
    },
    setFontScale: (next) => setFontScaleState(next),
    t: (key) => dictionaries[language][key] || dictionaries.pt[key] || key,
  }), [theme, language, highContrast, reducedMotion, readingProfile, fontScale, isAccessibilityOnboardingOpen]);

  return <PreferencesContext.Provider value={value}>{children}</PreferencesContext.Provider>;
}

export function usePreferences() {
  const ctx = useContext(PreferencesContext);
  if (!ctx) throw new Error('usePreferences must be used within PreferencesProvider');
  return ctx;
}
